import type { FastifyPluginAsync } from 'fastify';
import { and, count, eq, type SQL } from 'drizzle-orm';
import { AttentionActionSchema } from '@jevi-ops/shared/schemas';
import { getDb } from '../lib/db.js';
import { attention_items } from '../db/schema.js';
import { ATTENTION_LIST_ORDER } from '../lib/attention.js';

// /api/attention/* — read + lifecycle for Attention Engine items. The items
// are generated by the daily cron (see lib/attention.ts); this route surfaces
// them and applies snooze / dismiss / acted-on / reactivate.

export const attentionRoutes: FastifyPluginAsync = async (app) => {
  app.addHook('preHandler', app.requireAuth);

  // List — defaults to active, highest score first. Pass status=snoozed etc.
  // to inspect other buckets, or all=true for everything.
  app.get<{ Querystring: { status?: string; urgency?: string; limit?: string; all?: string } }>(
    '/api/attention',
    async (req) => {
      const limit = Math.min(parseInt(req.query.limit ?? '200', 10) || 200, 500);
      const conds: SQL[] = [];
      if (req.query.all !== 'true') {
        conds.push(eq(attention_items.status, req.query.status ?? 'active'));
      } else if (req.query.status) {
        conds.push(eq(attention_items.status, req.query.status));
      }
      if (req.query.urgency) conds.push(eq(attention_items.urgency, req.query.urgency));
      const items = await getDb().query.attention_items.findMany({
        where: conds.length ? and(...conds) : undefined,
        orderBy: ATTENTION_LIST_ORDER,
        limit,
      });
      return { items };
    },
  );

  // Count of active items — cheap, for the nav badge.
  app.get('/api/attention/count', async () => {
    const [row] = await getDb()
      .select({ n: count() })
      .from(attention_items)
      .where(eq(attention_items.status, 'active'));
    return { active: row?.n ?? 0 };
  });

  // Apply a lifecycle action.
  app.patch<{ Params: { id: string } }>('/api/attention/:id', async (req, reply) => {
    const parsed = AttentionActionSchema.safeParse(req.body);
    if (!parsed.success) {
      return reply.code(400).send({ error: 'invalid_payload', details: parsed.error.flatten() });
    }
    const now = new Date().toISOString();
    let update: Partial<typeof attention_items.$inferInsert>;
    switch (parsed.data.action) {
      case 'snooze': {
        const until =
          parsed.data.until ??
          new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
        update = { status: 'snoozed', snoozed_until: until };
        break;
      }
      case 'dismiss':
        update = { status: 'dismissed', dismissed_at: now };
        break;
      case 'acted_on':
        update = {
          status: 'acted_on',
          acted_on_at: now,
          acted_on_action: parsed.data.acted_on_action ?? null,
        };
        break;
      case 'reactivate':
        update = { status: 'active', snoozed_until: null, dismissed_at: null, last_surfaced_at: now };
        break;
    }
    const [row] = await getDb()
      .update(attention_items)
      .set(update)
      .where(eq(attention_items.id, req.params.id))
      .returning();
    if (!row) return reply.code(404).send({ error: 'not_found' });
    return row;
  });
};
