import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { SourcePanel } from './SourcePanel';
import type { MaintenanceItem } from '@/lib/api';
import type { SourceWithCandidates } from './types';
const actions = vi.hoisted(() => ({ load: vi.fn(), accept: vi.fn(), save: vi.fn(), add: vi.fn(), removeSource: vi.fn(), removeCandidate: vi.fn() }));
vi.mock('./actions', () => ({ loadSourcesAction: actions.load, acceptSourceCandidateAction: actions.accept, saveSourceCandidateAction: actions.save, addSourceAction: actions.add, removeSourceAction: actions.removeSource, removeSourceCandidateAction: actions.removeCandidate }));
const assetId = '00000000-0000-0000-0000-000000000002';
const itemId = '00000000-0000-0000-0000-000000000003';
const source: SourceWithCandidates = { id: 'source-link', source_id: 'source', label: 'Old receipt', kind: 'text', media_type: 'text/plain', size_bytes: 100, content_hash: 'hash', received_at: '2026-01-01T00:00:00Z', asset_id: assetId, session_id: null, processing_status: 'retained', url: null, download_url: '/api/sources/source-link/content', candidates: [{ id: 'candidate', source_link_id: 'source-link', revision: 2, status: 'pending', receipt: null, candidate: { label: 'Oil service', date_text: 'March 2024', date_precision: 'month', original_reading: 1000, original_unit: 'mi' } }] };
afterEach(() => { cleanup(); vi.clearAllMocks(); });
it('retains draft sources while refusing to apply history before the vehicle commit', () => {
  render(<SourcePanel subject={{ session_id: 'draft' }} initialSources={[source]} />);
  expect((screen.getByText('Review for historical recording') as HTMLButtonElement).disabled).toBe(true);
  expect(screen.getByText(/Save the vehicle first/)).toBeTruthy();
  expect(screen.getByText('Download original').getAttribute('href')).toBe('/api/sources/source-link/content');
  expect(actions.accept).not.toHaveBeenCalled();
});
it('requires exact date, reviewed conversion and selected work before recording historical evidence', async () => {
  const item = { id: itemId, name: 'Oil change', policy: 'interval' } as MaintenanceItem;
  actions.accept.mockResolvedValue({ error: 'Historical record changed; review again.' });
  render(<SourcePanel subject={{ asset_id: assetId }} meterUnit="km" items={[item]} visits={[]} today="2026-09-11" initialSources={[source]} />);
  fireEvent.click(screen.getByText('Review for historical recording'));
  const record = screen.getByText('Record reviewed history') as HTMLButtonElement;
  expect(record.disabled).toBe(true);
  expect((screen.getByLabelText('Actual service date') as HTMLInputElement).value).toBe('');
  fireEvent.change(screen.getByLabelText('Actual service date'), { target: { value: '2024-03-12' } });
  fireEvent.click(screen.getByLabelText(/I confirmed this exact service date/));
  fireEvent.click(screen.getByText('Use this converted value'));
  expect((screen.getByLabelText(/Accepted odometer \(km\)/) as HTMLInputElement).value).toBe('1609.34');
  fireEvent.click(screen.getByLabelText(/I reviewed the original units/));
  fireEvent.click(screen.getByLabelText(/Oil change/));
  fireEvent.change(screen.getByLabelText('Invoice total'), { target: { value: '125' } });
  fireEvent.change(screen.getByLabelText('Original currency'), { target: { value: 'USD' } });
  fireEvent.click(screen.getByLabelText(/I reviewed the source, selected work/));
  expect(record.disabled).toBe(false);
  fireEvent.click(record);
  await waitFor(() => expect(actions.accept).toHaveBeenCalledOnce());
  expect(actions.accept.mock.calls[0]?.[2]).toMatchObject({ expected_revision: 2, date_confirmed: true, unit_conversion_confirmed: true, visit: { visited_on: '2024-03-12', meter: 1609.34, currency: 'USD', total: 125, lines: [{ item_id: itemId }] } });
  expect(await screen.findByText('Historical record changed; review again.')).toBeTruthy();
  expect((screen.getByLabelText('Actual service date') as HTMLInputElement).value).toBe('2024-03-12');
  expect(source.candidates[0]?.candidate.date_text).toBe('March 2024');
});
