'use server';

import { createHash, randomUUID } from 'node:crypto';
import { revalidatePath } from 'next/cache';
import { ApiError, capturesApi } from '@/lib/api';
import { shapeInterpret, type CaptureOutcome } from '@/lib/capture-result';

// Durable capture server actions (capture program, Gate B).
//
// Step 1 — save: the durable receipt comes back and is rendered before any
// model runs. Step 2 — interpret: a separate call whose result updates the
// same chip. A hung model therefore never delays "Saved to Jevi Ops", and
// closing the portal after step 1 leaves the capture retrievable in
// Inbox › Captures.
//
// Ids (operation/capture/attachment) and captured_at are generated by the
// browser and held until the save is confirmed, so a retry replays the
// identical envelope instead of duplicating (a fresh timestamp would change
// the ledger digest and be refused as operation_id_reused).

export type SaveResult = Extract<CaptureOutcome, { kind: 'server_saved' | 'upload_incomplete' | 'status_unknown' | 'save_failed' }>;

const PROTOCOL = 1 as const;
const SUPPORTED_MEDIA = new Set(['audio/webm', 'audio/mp4', 'audio/m4a', 'audio/wav', 'audio/ogg', 'image/jpeg', 'image/png', 'image/webp']);

function errorCode(err: unknown): string {
  if (err instanceof ApiError) return ((err.body as { error?: string } | null)?.error) ?? `http_${err.status}`;
  return 'network_error';
}

function normalizeMediaType(raw: string): string | null {
  const base = raw.toLowerCase().split(';')[0]!.trim();
  const mapped = base === 'audio/x-m4a' ? 'audio/m4a' : base === 'audio/x-wav' || base === 'audio/wave' ? 'audio/wav' : base === 'video/webm' ? 'audio/webm' : base === 'image/jpg' ? 'image/jpeg' : base;
  return SUPPORTED_MEDIA.has(mapped) ? mapped : null;
}

export async function saveTextCapture(text: string, ids: { operationId: string; captureId: string; capturedAt: string }): Promise<SaveResult> {
  const trimmed = text.trim();
  if (!trimmed) return { kind: 'save_failed', message: 'Nothing to save.' };
  try {
    const res = await capturesApi.create({
      protocol_version: PROTOCOL,
      operation_id: ids.operationId,
      command: 'capture.create',
      payload: {
        capture_id: ids.captureId, kind: 'text', intent: 'capture_only', modality: 'typed', text: trimmed,
        captured_at: ids.capturedAt, client: { name: 'web', surface: 'portal-text' },
      },
    });
    revalidatePath('/inbox');
    return { kind: 'server_saved', captureId: res.receipt.capture_id, message: 'Saved to Jevi Ops.' };
  } catch (err) {
    return { kind: 'save_failed', message: `Could not save: ${errorCode(err)}` };
  }
}

// FormData fields: audio (Blob), operation_id, capture_id, attachment_id,
// finalize_operation_id, captured_at — all client-generated and stable
// across retries.
export async function saveAudioCapture(formData: FormData): Promise<SaveResult> {
  const audio = formData.get('audio');
  const ids = ['operation_id', 'capture_id', 'attachment_id', 'finalize_operation_id'].map((k) => String(formData.get(k) ?? ''));
  const [operationId, captureId, attachmentId, finalizeOperationId] = ids;
  const capturedAt = String(formData.get('captured_at') ?? '') || new Date().toISOString();
  if (!(audio instanceof Blob) || audio.size === 0) return { kind: 'save_failed', message: 'No audio attached.' };
  if (ids.some((v) => !v)) return { kind: 'save_failed', message: 'Missing capture identifiers.' };
  const mediaType = normalizeMediaType(audio.type || 'audio/webm');
  if (!mediaType) return { kind: 'save_failed', message: `Unsupported recording type: ${audio.type || 'unknown'}.` };
  const bytes = new Uint8Array(await audio.arrayBuffer());
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  const kind = mediaType.startsWith('image/') ? 'image' : 'audio';

  try {
    await capturesApi.create({
      protocol_version: PROTOCOL,
      operation_id: operationId!,
      command: 'capture.create',
      payload: {
        capture_id: captureId!, kind, intent: 'capture_only', modality: kind === 'image' ? 'photo' : 'spoken',
        captured_at: capturedAt, client: { name: 'web', surface: 'portal-voice' },
        attachments: [{ attachment_id: attachmentId!, media_type: mediaType as 'audio/webm', size_bytes: bytes.length, sha256 }],
      },
    });
  } catch (err) {
    return { kind: 'save_failed', message: `Could not save: ${errorCode(err)}` };
  }
  // From here the server holds only a reservation. Nothing below may report
  // "saved" until finalize confirms every attachment was verified.
  try {
    await capturesApi.upload(attachmentId!, bytes);
  } catch (err) {
    return { kind: 'upload_incomplete', captureId: captureId!, message: `Upload incomplete — recording not yet saved to Jevi Ops (${errorCode(err)}). Retry to resend it.` };
  }
  const finalize = { protocol_version: PROTOCOL, operation_id: finalizeOperationId!, command: 'capture.finalize' as const, payload: { capture_id: captureId! } };
  try {
    const res = await capturesApi.finalize(captureId!, finalize);
    if (res.receipt.capture_id !== captureId || res.receipt.receipt_kind !== 'server_saved') {
      return { kind: 'upload_incomplete', captureId: captureId!, message: 'Upload incomplete — the server has not confirmed the recording yet.' };
    }
  } catch (err) {
    if (err instanceof ApiError) {
      return { kind: 'upload_incomplete', captureId: captureId!, message: `Upload incomplete — recording not yet saved to Jevi Ops (${errorCode(err)}). Retry to resend it.` };
    }
    // The finalize response was lost: the same operation id tells us what
    // actually happened. No guessing in either direction.
    try {
      const op = await capturesApi.operation(finalizeOperationId!);
      if (op.operation.disposition !== 'applied') return { kind: 'upload_incomplete', captureId: captureId!, message: 'Upload incomplete — finalization was not applied. Retry to resend it.' };
    } catch (lookup) {
      try {
        const detail = await capturesApi.get(captureId!);
        if (detail.capture.storage_state !== 'complete') return { kind: 'upload_incomplete', captureId: captureId!, message: 'Upload incomplete — recording not yet saved to Jevi Ops. Retry to resend it.' };
      } catch {
        return { kind: 'status_unknown', captureId: captureId!, message: `Checking save status… (${errorCode(lookup)})` };
      }
    }
  }
  revalidatePath('/inbox');
  return { kind: 'server_saved', captureId: captureId!, message: 'Saved to Jevi Ops.' };
}

export async function interpretSavedCapture(captureId: string): Promise<CaptureOutcome> {
  try {
    const res = await capturesApi.interpret(captureId);
    revalidatePath('/');
    revalidatePath('/domains');
    revalidatePath('/inbox');
    return shapeInterpret(res);
  } catch (err) {
    return { kind: 'pending', captureId, state: 'queued', errorCode: errorCode(err), message: 'Saved to Jevi Ops. Interpretation is pending — see Inbox › Captures.' };
  }
}

export async function retryInterpretationAction(captureId: string, expectedAttemptNo: number): Promise<{ ok: boolean; message: string }> {
  try {
    const res = await capturesApi.retry(captureId, {
      protocol_version: PROTOCOL, operation_id: randomUUID(), command: 'capture.retry_interpretation',
      payload: { capture_id: captureId, expected_attempt_no: expectedAttemptNo },
    });
    revalidatePath('/');
    revalidatePath('/inbox');
    revalidatePath(`/inbox/captures/${captureId}`);
    const shaped = shapeInterpret(res);
    const message = 'summary' in shaped ? shaped.summary : 'message' in shaped ? shaped.message : `Ambiguous: ${shaped.field}. Review it below.`;
    return { ok: res.processing_state === 'committed', message };
  } catch (err) {
    return { ok: false, message: `Retry refused: ${errorCode(err)}` };
  }
}
